# Generated by Django 5.1 on 2024-08-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
